# This is a basic workflow to show the manual trigger
name: Manual-Actions-Workflow

on: 
  workflow_dispatch

jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Say something
      run: Hi, I've been manually triggered!
