# This is a basic workflow to show the manual trigger
name: Manual-Actions-Workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      instance:
        description: Instance URL or name from config.yaml
        required: true
      region:
        description: 'Region metadata expected (na, emea, apac)'
        required: true
        default: na
      instanceType:
        description: 'Instance type (stg, dev)'
        required: true
        default: dev
jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Say something
      run: echo "Hi, I have been manually triggered!"
    
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
    - name: Manual Workflow Approval
      if: github.event.inputs.instancesType != 'dev'
      uses: trstringer/manual-approval@v1.8.0
      with:
           approvers: Er4ge
           secret: '${{github.TOKEN}}'
           minimum-approvals: 1
           issue-title: Testing the Approval process
           exclude-workflow-initiator-as-approver: false
           depends_on_job: 'Manual Workflow Approval'

            
   
